### ISSUE TITLE
TF Explorer offline nodes details inconsistency

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#100]
Tested on https://explorer.test.grid.tf

By checking the details of some offline nodes on the explorer. there appears to be some inconsistent information.

### Example 1

On Node 4 the details page doesn't show any Country details but shows the location on the distribution map.

![image](https://user-images.githubusercontent.com/101194226/163708426-efe9be0b-04f6-431b-8b59-011c81d4ddd3.png)

### Example 2

On Node 29 the details page shows Country Details and also shows the location on the distribution map.

![image](https://user-images.githubusercontent.com/101194226/163708510-816e03a8-d769-4946-bc9d-933149a53d6c.png)

### Example 3

On Node 80 the dtails page shows Country Details but there's a problem rendering the country flag.

![image](https://user-images.githubusercontent.com/101194226/163708576-6d02c007-d16f-4b3c-803c-16d31bd16816.png)

**Comment by mohamedamer453** [comment]
This issue is still available in the dashboard with the same exact nodes mentioned on testnet.

**Comment by khaledyoussef24** [comment]
the problem is still there 
##node 80
there is a problem in the flag icon
![Screenshot from 2022-08-23 02-23-47](https://user-images.githubusercontent.com/110984055/186042183-deadb43e-eb7a-4638-bb7c-615e3cf9399c.png)
##node 4
no country only on the map
![Screenshot from 2022-08-23 02-23-35](https://user-images.githubusercontent.com/110984055/186042294-ba9880f2-a823-4f04-aef0-4dc7209302cf.png)
##

**Comment by mohamedamer453** [comment]
Verified on devnet.
i checked the details of all the offline nodes on devnet and all of them were consistent and the icons were rendered correctly.

Will re-verify this again on testnet with the same nodes mentioned above once it's released there and will re open this issue if there're any issues.
