### ISSUE TITLE
Accounts - Nodes page 

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#108]
This page is meant for dedicated nodes but the title on the page tells me "Your nodes"

Please change to "Dedicated Nodes"

Maybe also change the 'Account-Nodes' link to 'Dedicated Nodes"

![image](https://user-images.githubusercontent.com/88312671/181008117-92352551-cc4a-4dc4-af91-a8198177ce07.png)

**Comment by mohamedamer453** [comment]
Verified.

The title was changed to `Dedicated nodes` and the `Account - ` was removed but the name in the items list still says `Nodes` not `Dedicated Nodes` which might be a bit confusing since the users can access their nodes form the dashboard in case they have ones.

![image](https://user-images.githubusercontent.com/101194226/181265463-7cb1b75a-58dc-46f8-88e9-718f66aa9558.png)

**Comment by amiraabouhadid** [comment]
noted and done, thanks

**Comment by mohamedamer453** [comment]
Verified. 

![image](https://user-images.githubusercontent.com/101194226/181589897-142bcdf2-2e1b-41bf-96cd-43b2ad8e8a81.png)
