### ISSUE TITLE
Large decimal numbers cause transfer TFT error.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#162]
The amount (TFT) input in Transfer TFTs or withdraw TFT permits large decimals numbers (greater than 6 decimal digits), and submit is enabled, yet it returns an error.  

The decimal amount matched my twin's balance exactly.
![test 8](https://user-images.githubusercontent.com/109473873/183415956-98cf90cd-b15e-464e-a591-9649ea1984dd.png)

Also, while attempting to withdraw TFT, the button continues to load.
![image](https://user-images.githubusercontent.com/109473873/183418589-eb57ab8c-35f4-4583-b5ce-83792928a756.png)

**Comment by mohamedamer453** [comment]
The issue was fixed in the `Withdraw TFT` Page and a validation of a maximum of 3 decimals was added to this field.

![image](https://user-images.githubusercontent.com/101194226/187178500-bc359573-a508-4bc7-8f9f-0c812d5e4131.png)
 
but it's still available in the `Transfer` page

![image](https://user-images.githubusercontent.com/101194226/187178856-7daa5f8e-77a7-4aaf-83cf-7a9c362dc537.png)

**Comment by mohamedamer453** [comment]
Verified.

The same validation that was added for the `Withdraw` page was also added in the `Transfer` page.

![image](https://user-images.githubusercontent.com/101194226/187235288-c6dac166-44d0-41dc-9fb1-2ea3f4f75e3a.png)
