### ISSUE TITLE
QA: create initial framework with Cypress for tfgrid_dashboard automation testing

### ISSUE THREAD

**Issue by ramezsaeed** [threefoldtecharchive/tfgrid_dashboard#163]
- [ ] create the initial framework for testing with Cypress.
- [ ] write the first test case from teslodge coverage.
- [ ] link the test to run with github actions

**Comment by mohamedamer453** [comment]
Initial framework for cypress was created (for the explorer part) in #175 with an example verifying the stats page from the grid_proxy and a github workflow that runs the tests daily.

for the portal part i'm still stuck due to the portal using `polkadot.js` extension and cypress currently doesn't support extensions, so i'm currently looking for another solution/workaround for the extension part.

**Comment by mohamedamer453** [comment]
Another initial framework using selenium was also added in #200 to support the portal part that needed `polkadot.js` extension since cypress didn't have extension support and all the workarounds were complicated/inefficient since they used completely different frameworks other than cypress to partially support the extension.
