### ISSUE TITLE
Node specs didn't update in portal, only explorer

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#270]
Farmer reports that after adding additional hdd to his mainnet node 628, the change is only reflected in the explorer section of the dashboard, not in the portal section.

**Comment by zaelgohary** [comment]
I just checked the retrieved data from the portal & the explorer. they both are the same. Can you ask the farmer to provide a screenshot if the issue is still there?

Data shown in Explorer:
![image](https://user-images.githubusercontent.com/40770501/191522580-113757fb-d1b0-4952-a24a-4ac9293197e5.png)

Data shown in Portal: 
![image](https://user-images.githubusercontent.com/40770501/191522830-45b715b9-90f5-418d-93c3-a1f856518811.png)

**Comment by scottyeager** [comment]
The farmer is still experiencing this issue. Here's the screenshot they provided:

![095A2F81-8ADE-4B28-804D-2F358479DD5A](https://user-images.githubusercontent.com/17682591/191871851-7d841853-b056-43b7-a95b-cbfdc70f9a17.jpeg)

Farmer also mentioned moving the node, and the city updated while HRU has not.

**Comment by zaelgohary** [comment]
This issue is already fixed [here](https://github.com/threefoldtech/tfgrid_dashboard/issues/182). It will be reflected on main net once released.

**Comment by A-Harby** [comment]
Verifed on Devnet and Testnet.

Test steps: [TC832 - Show Node Infromation](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631924) - [TC848 - Verify Node Information from grid_proxy](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3632255)
