### ISSUE TITLE
Filters id Farms work no correclty 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtecharchive/tfgrid_dashboard#28]
https://explorer.test.grid.tf/farms
![Peek 2022-06-04 12-54](https://user-images.githubusercontent.com/106578096/171994326-556ccc2f-dc60-491f-ba70-7edccdf13755.gif)

No.182 - Test case: TC231
Version v1.4.2
Deployed on Testnet

**Comment by rkhamis** [comment]
@MohamedElmdary can you verify this isn't happening in the new dashboard?

**Comment by mohamedamer453** [comment]
This issue is still not fixed and this issue mainly happens due to the farms page filtering itself.
Because the results don't change back when you remove the current filter. and before applying a second filter you need to clear the input and press on `Apply Filter` to load all the results or to click on apply filter 2 times since the first time loads all the results.

I think this would be better solved by applying the same filtering done in the nodes page to the farms page since the nodes page filtering is working properly and for the sake of consistency.

**Comment by zaelgohary** [comment]
The filtering works just fine. It just needs a chip label to filter by it otherwise it'll consider you filtered by an empty string and returns all available farms. You can filter by multiple farms at once as shown below or by an individual farm, all you need to do is to hit enter before applying the filtering to create a chip label. 

![image](https://user-images.githubusercontent.com/40770501/181479246-f7b02aa7-2817-472c-9c7f-7dbaa8ab1a1d.png)
