### ISSUE TITLE
Filtering in nodes isn't working properly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#304]
# Nodes filtering 
Sometimes filtering works fines but most of the cases isn't working at all or retrieve randomized nodes and have to refresh page to reload and work properly.

## Node ID

Filtering is working here fine but after many tries, it wont work again for no reason.
![image](https://user-images.githubusercontent.com/109473873/196460628-505eea7f-9151-4ae3-ba63-cdd28186523c.png)

##  Farm IDs 

Same as Node ID, it just stop working
![image](https://user-images.githubusercontent.com/109473873/196465340-47b7d2f4-ee19-40b0-82e1-a871ba2cedd1.png)

## Farm Name

Filtering isn't case sensitive
![image](https://user-images.githubusercontent.com/109473873/196456373-cb23cd5f-f0e4-46ea-ac88-ffb49742bfeb.png)
Can't filter using some chars of the name
![image](https://user-images.githubusercontent.com/109473873/196456844-080cb955-40d6-4355-815c-49a61eb9a4ca.png)

##  Country Full Name 

Filtering isn't case sensitive
![image](https://user-images.githubusercontent.com/109473873/196457059-5a101fe3-cdea-4558-839b-28f817119aa1.png)

##  Storage (GB) -  Hard Storage (GB) -  Memory (GB)  - CPU (Cores) 

Can't figure how to use it and every number is just retrieve random nodes.
There is nodes with equal, higher or less amount.
![image](https://user-images.githubusercontent.com/109473873/196470438-6b108912-8229-4d00-b64d-3a8b3463442c.png)
![image](https://user-images.githubusercontent.com/109473873/196470670-b38151c9-4fce-4ce1-bc4b-4965ed191cba.png)
![image](https://user-images.githubusercontent.com/109473873/196471206-da248ea4-9085-4aa9-9de0-a476d742804a.png)
![image](https://user-images.githubusercontent.com/109473873/196471357-7c7a05e9-0784-4b62-8542-86e1e46ab7bd.png)

**Comment by Omarabdul3ziz** [comment]
### node id, farm ids
you are on the second page. if you go back you will find all the nodes.
![image](https://user-images.githubusercontent.com/32527347/197393534-e4403bbf-d633-45b4-a3d3-6d3195541715.png)

### farm/country name
- it should not work for the substring of the name or a different letters case.
  since the explorer only maps the filter key to gridproxy query. and gridproxy literally searches if the query value matches the DB value or not.
- but there is a feature request on gridproxy to implement that. [https://github.com/threefoldtech/tfgridclient_proxy/issues/175](https://github.com/threefoldtech/tfgridclient_proxy/issues/175)
        
### resources
- the filter searches the nodes with `FREE resources` equal to or more than the input value.
  take node 11 for example from https://gridproxy.dev.grid.tf/nodes/11 
  ![image](https://user-images.githubusercontent.com/32527347/197393402-3baf541b-59f6-474a-807a-1dbf7911423c.png)
  `total_sru - used_sru = 512110190592 - 458412261376 = 53697929216/1024^3 = 50 GB`
  ![image](https://user-images.githubusercontent.com/32527347/197393558-6c79626b-2fad-42ec-87af-031489cf667f.png)
- but the value shown in the table is the total amount of the resources the node has
- I added the `Free` word on the names of the filters to clear the confusion

**Comment by A-Harby** [comment]
> ### node id, farm ids
> you are on the second page. if you go back you will find all the nodes.

That was the actual case but It is an issue as it should not direct me to a second page if only the result can be listed in one page.

> ### farm/country name
> * it should not work for the substring of the name or a different letters case.

Before that, substring was promoting all the farms with the same string.
![image](https://user-images.githubusercontent.com/109473873/197397152-4ec27dc5-f046-417a-8903-7124b66be7aa.png)


>   since the explorer only maps the filter key to gridproxy query. and gridproxy literally searches if the query value matches the DB value or not.
> * but there is a feature request on gridproxy to implement that. [Search query cities and countries needs to be case sensitive  tfgridclient_proxy#175](https://github.com/threefoldtech/tfgridclient_proxy/issues/175)
 
This issue had been solved before in [here](https://github.com/threefoldtech/tfgrid_dashboard/issues/112) 

> ### resources
> * the filter searches the nodes with `FREE resources` equal to or more than the input value.
>   take node 11 for example from https://gridproxy.dev.grid.tf/nodes/11
>   `total_sru - used_sru = 512110190592 - 458412261376 = 53697929216/1024^3 = 50 GB`
> * but the value shown in the table is the total amount of the resources the node has
> * I added the `Free` word on the names of the filters to clear the confusion

Yes that was confusing, will verify that once PR is merged.
And could we change resource name (Storage (GB) - Hard Storage (GB) - Memory (GB) - CPU (Cores)) to be the same as in node table headers, would be more clarifying to what is being filtered. 
![image](https://user-images.githubusercontent.com/109473873/197397713-8abe05b5-1edf-4a09-b149-85c82f447994.png)

**Comment by Omarabdul3ziz** [comment]
- Yes. it is not good to view the `n` page where there is only one page. added a fix for that check the updates in the attached pr.
- The previous implementation was fetching all the nodes to be on the browser side and then filtering/sorting/paginating all that done on the client side. but since this changed it should be done on gridproxy. follow the issue there.
- i think it is more clear like that especially after adding the `Free ` prefix. changes the names of the filters to be as the tables headers will make it confusing. what do you think? @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
I think we should first change `storage` to `SSD` and `hard storage` to `HDD`.
IMO CPU, memory, SSD, and HDD make more sense for the user, but they will need to be changed in many places in the dashboard

**Comment by Omarabdul3ziz** [comment]
PR updated with changing the filters names to `Free_SRU`, `Free_HRU`, `Free_CRU`, `Free_MRU`,

**Comment by A-Harby** [comment]
Verified on Devnet.
Filtering is now more clear after specifying Total and free resource.
![image](https://user-images.githubusercontent.com/109473873/200874518-dda8532e-05ab-4fa3-865e-cecfaa6a3dd6.png)

Filtering works fine.

Node ID 
![image](https://user-images.githubusercontent.com/109473873/200874657-e36990c7-3687-4922-a81a-68352d1a80af.png)
Twin ID
![image](https://user-images.githubusercontent.com/109473873/200874809-73cb466a-d6a0-4f42-bf2b-7ce2ab57a8c5.png)
Farm ID
![image](https://user-images.githubusercontent.com/109473873/200874904-60357124-1ca8-4b5d-9fba-cafc97dc3a78.png)
Farm Name
![image](https://user-images.githubusercontent.com/109473873/200875004-40e71ab3-b4d1-432b-93a6-4e9182730875.png)
Country Name
![image](https://user-images.githubusercontent.com/109473873/200875192-72f8b187-b823-4402-83fa-016b64262fe3.png)

**Comment by A-Harby** [comment]
But in Free Resources, Node have less value than the filter. 

Node 18 and 20.
![image](https://user-images.githubusercontent.com/109473873/200875758-6d19f706-02a5-424c-ac48-891163679d6a.png)

**Comment by AhmedHanafy725** [comment]
there is no filter for `free_cru` in gridproxy. please remove it

**Comment by A-Harby** [comment]
Verified on Devnet.

Free resource filters works fine.
![image](https://user-images.githubusercontent.com/109473873/201118311-8067a51e-3bc9-4d61-8635-7ec5818f43d5.png)
And Free CRU is removed.
![image](https://user-images.githubusercontent.com/109473873/201118512-6b52d3de-2660-4463-8a4a-ed7b544e0be1.png)

Test steps:[TC834 - Filter Nodes by Resources](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631928) - [TC834 - Filter Nodes by Resources](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631928) - [TC836 - Filter Nodes by Farm ID](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3631947) - [TC837 - Filter Nodes by Twin ID](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3632023) - [TC840 - Filter Nodes by number of free Public IPs](https://app.testlodge.com/a/26076/projects/40893/suites/209098?expand_section=348399#case_3632034)
