### ISSUE TITLE
Dashboard shows a very low number of dedicated nodes available.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtecharchive/tfgrid_dashboard#367]
Based on the description of how dedicated nodes are available:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/13766992/199877416-3b192582-d1e7-448e-a0e0-a2afe4b6e327.png">

We should have way more dedicated nodes available than 50:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/13766992/199877512-32ae88b7-091b-4f9d-8a88-b53c71be437c.png">

The total number of nodes in mainnet is: >5000
<img width="897" alt="image" src="https://user-images.githubusercontent.com/13766992/199877690-e4fd8914-5570-41c6-8beb-9b222576f179.png">

IT cannot be that less than 1% is available as a dedicated node.  Something must be wrong in the selection criteria for a node to qualify as a dedicated node

**Comment by xmonader** [comment]
@DylanVerstraete @Omarabdul3ziz please take a looks at this one. I don't believe the first flow of farmer marking their nodes as `dedicated` still a thing

**Comment by AhmedHanafy725** [comment]
dashboard fetches only the first page from gridproxy. it needs to get the other pages.
mainnet has 2772 rentable nodes, check the count in the headers of this query https://gridproxy.grid.tf/nodes?rentable=true&ret_count=true&status=up

**Comment by mohamedamer453** [comment]
Verified locally with the latest version on development but with the network changed to mainnet.

All of mainnet nodes are now appearing in the dedicated nodes tab.

![image](https://user-images.githubusercontent.com/101194226/201141254-ecef132b-f659-4bac-a21b-109f69f34671.png)

with the same number returned from this request https://gridproxy.grid.tf/nodes?rentable=true&ret_count=true&status=up

![image](https://user-images.githubusercontent.com/101194226/201141462-58661f74-0271-40dd-bd1d-6b51528cdc31.png)


since the only way to verify this issue now was locally i'll leave it open until it's released on mainnet and i can verify that it's working without any issues.

**Comment by mohamedamer453** [comment]
Verified on mainnet.

The issue was fixed and now the dashboard displays the same number returned from the grid proxy

![image](https://user-images.githubusercontent.com/101194226/203299816-aa0be006-e618-46c6-938c-a0b8b898055a.png)

```
https://gridproxy.grid.tf/nodes?rentable=true&ret_count=true&status=up
```

![image](https://user-images.githubusercontent.com/101194226/203299622-d9ab60b4-9645-4acc-b494-544f98ceee8b.png)
