### ISSUE TITLE
Separate list for reserved dedicated nodes

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#376]
### Description

Once you rent a dedicated node appears in the first 10 nodes if your lucky, otherwise it's further in the list. There is no real handy overview of how many and what nodes one has rented. If it appears, you can see it's your node only because it has an 'Unreserve' button. This is also not really clear.

![image](https://user-images.githubusercontent.com/88312671/200279383-3402622f-fe6d-49aa-983a-8c1ccb0f2f09.png)

### Implementation

Maybe we can create a separate list at the top on the same 'Dedicated Nodes' page, with all rented dedicated nodes

**Comment by mohamedamer453** [comment]
Verified locally with the latest version on development but with the network changed to mainnet. (since there are no dedicated nodes on devnet to try this on)

The dedicated nodes were separated into 3 different tabs

- Rentable 

   ![image](https://user-images.githubusercontent.com/101194226/201142421-b4bc992c-923d-4016-a764-48de59bdfe1c.png)

- Rented 

   ![image](https://user-images.githubusercontent.com/101194226/201142539-ce211e74-3978-43c6-9b8a-ce178c5c3776.png)

- Mine 

   ![image](https://user-images.githubusercontent.com/101194226/201142625-b47b06f0-57c4-41c2-9404-9415977732ee.png)

since the issue was verified on locally with the network changed to mainnet since there were no available nodes to rent on devnet. i'll leave it open until it's released on qanet and i can verify that it's working without any issues.

**Comment by mohamedamer453** [comment]
Re-verified on qanet. Dashboard v1.2.1, gridproxy v1.6.5

The new logic of the dedicated nodes table was applied and it's now separated into 3 different tabs.


- Rentable

   **https://gridproxy.qa.grid.tf/nodes?status=up&ret_count=true&page=1&size=10&rentable=true**

   ![image](https://user-images.githubusercontent.com/101194226/201513156-897acc9f-46a6-40cb-beaa-a2b04d7c7761.png)

- Rented

   **https://gridproxy.qa.grid.tf/nodes?status=up&ret_count=true&page=1&size=10&rented=true**

   ![image](https://user-images.githubusercontent.com/101194226/201513160-d0090584-2b10-4cce-b536-599131741602.png)

- Mine 

   ***https://gridproxy.qa.grid.tf/nodes?status=up&ret_count=true&page=1&size=10&rented_by=16***

   ![image](https://user-images.githubusercontent.com/101194226/201513182-86a8479d-7650-432e-8744-3ed26fb1b2db.png)

and for each tab you will find its corresponding endpoint from the gridproxy
