### ISSUE TITLE
(Mainnet Verification) Uptime percentage shown seems too low

### ISSUE THREAD

**Issue by scottyeager** [threefoldtecharchive/tfgrid_dashboard#466]
Farmer reported that the briefly shut down their node to make an upgrade, then noticed that the portal shows a larger than expected reduction in uptime:

![image](https://user-images.githubusercontent.com/17682591/213537249-e2bdd31e-13f1-4b9d-8dd5-c702130a0011.png)

I have my own script that checks the uptime events from GraphQL and reports periods of downtime. For this node in January, I see two times it went offline, for a total of about 70 minutes. This should correspond to less than 1% downtime.

```
Node 5174
----------------------

Node went offline: 2023-01-07 08:46:06
Downtime: 1835

Node went offline: 2023-01-16 07:23:30
Downtime: 2318
```

**Comment by DylanVerstraete** [comment]
So we can asume it's a code bug in the dashboard? 

somewhere here: https://github.com/threefoldtech/tfgrid_dashboard/blob/16f55c45b733b4b23482b19cbb5eee9159146928/src/portal/lib/nodes.ts#L51

I'm not sure, the calculations seems correct but maybe the data isn't fetched properly?

**Comment by DylanVerstraete** [comment]
@amiraabouhadid where is this `node.uptime` coming from? Is this field just extracted from graphql? Because in graphql the uptime is the total uptime since the node was last booted. In that case, we need to fetch uptime events for a given period and calculate the uptime like that.

**Comment by DylanVerstraete** [comment]
Maybe this can help:

1: Period starts are not always the first of the month, calculate the current period start by starting from the first period and incrementing with the duration of a period: https://github.com/threefoldtech/minting_v3/blob/ead7801b0245762cebecfd50afbbd59059ac0fab/src/period.rs#L10 maybe check: https://github.com/threefoldtech/minting_v3/blob/ead7801b0245762cebecfd50afbbd59059ac0fab/src/period.rs#L25

2: It's better to subtract downtime from the current period duration to get the uptime (so no need to access node.uptime)

**Comment by xmonader** [comment]
@amiraabouhadid please make sure to give that a look.

**Comment by amiraabouhadid** [comment]
Hey @DylanVerstraete please refer to this to see how the uptime was calculated https://github.com/threefoldtech/tfgrid_dashboard/issues/366#issuecomment-1323878588

**Comment by DylanVerstraete** [comment]
Yes, but it looks like the calculation is not correct (see my comments above)

**Comment by sabrinasadik** [comment]
Any updates on this? Getting some questions on chat about it

**Comment by amiraabouhadid** [comment]
Hey @sabrinasadik will look into it after rmb ts client as it is more urgent to release the client

**Comment by sameh-farouk** [comment]
Having a look at this

**Comment by sameh-farouk** [comment]
**Update**:
Thanks for lee to provide a brief explanation [here](https://github.com/threefoldtech/tfgrid_dashboard/issues/366#issuecomment-1304436906), I drafted a [PR](https://github.com/threefoldtech/tfgrid_dashboard/pull/551) based on his comment to fix this.

Can you take a look here at where the calculations are done @DylanVerstraete?
https://github.com/threefoldtech/tfgrid_dashboard/blob/a9d52c307034c7a732ea4dc81fe7ce7195b8c427/src/portal/lib/nodes.ts#L32-L85

Feel free to [review](https://github.com/threefoldtech/tfgrid_dashboard/pull/551) and let me know if something feels off.

**Comment by mohamedamer453** [comment]
This issue can't be verified until it reaches mainnet since the uptime percentage is only present there. once it reaches mainnet the uptime of the mentioned node `5174` should be checked again to see if it returned to its normal percentage or not.

**Comment by sameh-farouk** [comment]
> This issue can't be verified until it reaches mainnet since the uptime percentage is only present there. once it reaches mainnet the uptime of the mentioned node `5174` should be checked again to see if it returned to its normal percentage or not.

@mohamedamer453 This is no longer valid. with the recent patch the feature is enabled on all networks.

**Comment by sameh-farouk** [comment]
When I tried to verify the node uptime fix before releasing it to `devnet`, the nodes on `freefarm` were either completely down (0% uptime) or up (100% uptime) since the minting period started. I had no chance to verify the case when there is some downtime.
checking today, I found some nodes had a downtime recently and the downtime comes in negative so it increases the node up-time instead of decreasing it. will try to fix it asap. @AhmedHanafy725  shall I prioritize this?

![Screenshot from 2023-03-23 14-00-54](https://user-images.githubusercontent.com/42457449/227197827-cc2f9671-65b2-45b1-a108-6582740ff2f2.png)

**Comment by mohamedamer453** [comment]
> When I tried to verify the node uptime fix before releasing it to `devnet`, the nodes on `freefarm` were either completely down (0% uptime) or up (100% uptime) since the minting period started. I had no chance to verify the case when there is some downtime. checking today, I found some nodes had a downtime recently and the downtime comes in negative so it increases the node up-time instead of decreasing it. will try to fix it asap. @AhmedHanafy725 shall I prioritize this?
> 
> ![Screenshot from 2023-03-23 14-00-54](https://user-images.githubusercontent.com/42457449/227197827-cc2f9671-65b2-45b1-a108-6582740ff2f2.png)

Verified on devnet. 

The issue was fixed and the nodes are back to their normal uptime. for the same node that was originally mentioned in the comment `Node 13`

![image](https://user-images.githubusercontent.com/101194226/228812472-6bb054a4-4614-40f5-bf96-49d96c495667.png)

this node had some down time and the percentage was reflected correctly.

another case is `Node 24` which didn't send any uptime events since the current minting period so its uptime is `0`

![image](https://user-images.githubusercontent.com/101194226/228813026-d33dd49c-0abe-43bd-ac9c-cc49aaecfafe.png)
 
and finally the last case is `Node 14` with no down time so its uptime percentage is `100`

![image](https://user-images.githubusercontent.com/101194226/228813364-3520dba0-a2a4-468a-898a-55c9c0118f07.png)


I was going to leave this issue until it reaches mainnet to verify the uptime for the node that was originally mentioned in the issue but since the uptime percentage is back to all networks then there's no need to do that.

I'll close this issue but it would be great if @scottyeager could verify that the uptime of `node 5174` is reflected correctly once it reaches mainnet. And please feel free to reopen this issue if the uptime percentage still seems low.

**Comment by scottyeager** [comment]
Thanks @mohamedamer453. I'll keep an eye out for any further issue with this feature.
