### ISSUE TITLE
can't create a new twin on QA net

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtecharchive/tfgrid_dashboard#479]
### can't create a twin on QA net

steps to produce:

1. create a new polkadot account
2. go to the dashboard 
3. insert your ygg_ip
4. click on create twin
5. twin creation will fail
[Screencast from 01-26-2023 02:28:08 PM.webm](https://user-images.githubusercontent.com/110984055/214836804-db271a23-3d50-4843-9c0e-8dc152110602.webm)

**Comment by coesensbert** [comment]
There where some version differences between dev and qa, could you try again?

**Comment by zaelgohary** [comment]
I could create a twin and an IP but account details is not shown.

![image](https://user-images.githubusercontent.com/40770501/215317310-2dcac5a0-817d-4667-8889-2fec82f348d9.png)

I think this happens because the version is still not set on QA net as shown in the screenshot above. Should be solved once [this](https://github.com/threefoldtech/tf_operations/issues/1396) is closed.

**Comment by zaelgohary** [comment]
The issue is supposed to be solved now.

![image](https://user-images.githubusercontent.com/40770501/215327313-faeba738-639d-4eb6-a9e7-d257a5ac6f33.png)

**Comment by A-Harby** [comment]
Verified, issue was fixed and twin can be created successfully.
But retrieving twin data still have a error and it was reported in https://github.com/threefoldtech/tfgrid_dashboard/issues/474
