### ISSUE TITLE
Special char in farm name

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#494]
### Description

Farm name in node page explorer input accepts all chars

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/216318206-2c26799b-e310-4c33-876a-e7bc27f9b5d3.png)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid_dashboard/pull/519

**Comment by A-Harby** [comment]
Farm name does accept number in its name but it doesn't accept special char
![image](https://user-images.githubusercontent.com/109473873/227209556-4f3e5c99-9336-4faa-90b4-1b883785444c.png)

**Comment by Mahmoud-Emad** [comment]
@A-Harby Should be fixed in https://github.com/threefoldtech/tfgrid_dashboard/pull/608

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `Farm Name` field was updated to not accept special characters.

![image](https://user-images.githubusercontent.com/101194226/230896672-bf1c457f-61c5-4735-921c-4df2041fdc99.png)

And to accept digits since they are allowed in farm names.

![image](https://user-images.githubusercontent.com/101194226/230896787-ef83b0bb-3450-463c-8b13-6c91ec10894b.png)
