### ISSUE TITLE
User journey updates

### ISSUE THREAD

**Issue by xmonader** [threefoldtecharchive/tfgrid_dashboard#52]
First of all, I don't think the UX is great at this point. When you multiple accounts these all appear in the side bar and all of your accounts have submenus.. I think we need to approach this very differently. I'm looking at other project which are doing the same, creating a "portal" on their platform. Everybody uses the polkadot js extension as well.

First of all, let's have a profile Icon where I can select the account which I want to connect with instead of having every account in the sidebar:

![photo_2022-06-20_13-19-05](https://user-images.githubusercontent.com/17138347/174590664-e136d2a7-3d8d-4743-b027-3e98fcd22476.jpg)

![photo_2022-06-20_13-19-04](https://user-images.githubusercontent.com/17138347/174590666-1e8e5d09-bcc4-4530-81c8-c6173a7bad7c.jpg)
![photo_2022-06-20_13-19-11](https://user-images.githubusercontent.com/17138347/174590668-fe76d2cc-041e-486d-927b-1f82c6033a2d.jpg)

Secondly, I think we need a prettier font. While the standard font is okay, a more beautiful font makes the world of difference. Think of a Roboto or Open sans, ..

**Comment by DylanVerstraete** [comment]
![Screenshot from 2022-06-20 13-23-33](https://user-images.githubusercontent.com/17138347/174591372-6074a30e-6aca-4eff-8dc4-fe9fda8f05d0.png)
![Screenshot from 2022-06-20 13-23-18](https://user-images.githubusercontent.com/17138347/174591382-134ef30f-19c7-4d21-81c2-ed2423d2c4ee.png)

I don't know what this `Automatically` button does, I don't even want to press it because I don't know what is going to happen..

A link to more information should not be displayed in a button. Preferably have an `info` link which opens a modal where some stuff is explained (or popover info icons)

**Comment by DylanVerstraete** [comment]
Also, my TFT balance is the **most** important thing I want to see as u user. Now it's crammed in the right bottom. Imagine having millions of TFT and then it also needs to fit in that small corner. (We had the same issue in other wallets) 

It should be the first thing I see when I log in to the page. Preferably in the middle of the screen (with a price attached)

Can use https://tftprice.grid.tf/ as a price oracle

**Comment by sabrinasadik** [comment]
Would love to brainstorm about this again and see what's possible / what's needed.

**Comment by sasha-astiadi** [comment]
would love to  have a test / tryout session as i previously worked as ux designer/researcher @sabrinasadik
