### ISSUE TITLE
UI changes - Buttons should not be all caps 

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtecharchive/tfgrid_dashboard#54]
Nothing should be in all caps (ThreeFold Chain - Portal - Explorer - Hub) 
Would look nice if we can make some rounded buttons (see example) 
![Screenshot 2022-06-17 at 11 11 54](https://user-images.githubusercontent.com/31733464/174267362-3898959d-5b3d-4451-add2-8d864e3dddee.png)
![Screenshot 2022-06-17 at 10 54 58](https://user-images.githubusercontent.com/31733464/174267367-429367f1-42a6-4e7f-ab64-b7f4c7e8af41.png)

**Comment by mohamedamer453** [comment]
Verified.

All the options in the sidebar were Capitalized instead of being all in caps. and the buttons are now rounded.

![image](https://user-images.githubusercontent.com/101194226/183286200-845d0e81-60c1-4715-89d5-2aa64d6d7be1.png)


But the title `ThreeFold Chain` and the account names are still all in caps.

![image](https://user-images.githubusercontent.com/101194226/183286483-040c4331-5159-4128-bdbf-1dfa92cc9ae1.png)

**Comment by mohamedamer453** [comment]
Verified.

The title and account names were fixed.

![image](https://user-images.githubusercontent.com/101194226/183288669-3faf9a4f-0808-4044-b5f1-69ec7c9aca47.png)

![image](https://user-images.githubusercontent.com/101194226/183288615-306929d7-f4e9-4a4e-9ddb-05eb681594d7.png)
