### ISSUE TITLE
Stellar address is no longer accepted `Address not found`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtecharchive/tfgrid_dashboard#569]
### Description

Stellar address is no longer accepted, but they were, and they have TFT assets added to the account.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/225074736-de304834-3ab1-4709-9cac-efe89749d55b.png)
![image](https://user-images.githubusercontent.com/109473873/225075144-5c091659-92cb-4ef0-b5af-f2c92a10d5f1.png)

**Comment by Mahmoud-Emad** [comment]
This is not an issue, or not an issue from the dashboard, because the currently selected network for stellar is `main` which means if you sent a `testnet` account address it will raise an error `404` came from stellar itself, which means this is an invalid address.


so this [issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/571) should handle the stellar network, once it gets fixed I think the request will be sent to the right network.

**Comment by hossnys** [comment]
the fix deployed now on qanet please verify and close this one  https://github.com/threefoldtech/tf_operations/issues/1510 once verified

**Comment by A-Harby** [comment]
So now it gives an alert message to both main and testnet stellar address, and other error when stellar address pop up.
![image](https://user-images.githubusercontent.com/109473873/225584319-f135bf88-3d4f-484f-9eb2-df4f9b35b5e1.png)

**Comment by A-Harby** [comment]
Verified on Qanet, v1.4.0-rc7.
![image](https://user-images.githubusercontent.com/109473873/225588338-f3259bc5-5ae1-409a-a81b-a7cbe404f8a9.png)
